### ISSUE TITLE
so this is not really an issue but is there a way to change thethe purple color to like blue or something?

### ISSUE THREAD

**Issue by Firefox289** [Quest0/amoled#11]

**Comment by Firefox289** [comment]
as the title says

**Comment by Quest0** [comment]
Yes. That's called the accent color, and you can edit it in the theme.css file.
![image](https://user-images.githubusercontent.com/31394614/109396513-35cbd600-78ef-11eb-9753-712b58aea74c.png)
If you find a replacement color you like, copy it's RGB values into that area.
![image](https://user-images.githubusercontent.com/31394614/109396541-5c8a0c80-78ef-11eb-8116-5f47d7d22d6d.png)
Then hit save, and if you're already running the theme on BBD, your changes should take effect immediately.

Hope this helped.

**Comment by Firefox289** [comment]
thx

**Comment by Quest0** [comment]
Marking this as resolved. Please create an additional issue or contact me on Discord @ Quest#8775 if you have any other questions.
